version : "3.9"
services :
 flaskapp :
    build: .
    image: titanic-flask:latest
    ports:
    -"5000:5000"
    volumes:
    -.:/cloud
    links:
    - "postgres:db"
    depends_on:
     - postgres
    environment:
       FLASK_ENV: development
     
     
 postgres:
     image: postgres:latest
     environment:
        POSTGRES_USER: POSTGRES_USER
        POSTGRES_PASSWORD: POSTGRES_PASSWORD
        POSTGRES_DB: POSTGRES_DB
     restart: always